<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PMLDVBALAJID" failures="1" tests="2" name="Errro Validation Test" time="42.013" errors="0" timestamp="2024-05-19T21:50:29 IST">
  <testcase classname="BalajiSoft.SaleniumDesign.tests.ErrroValidationTest" name="LoginErrorValidation" time="1.064"/>
  <testcase classname="BalajiSoft.SaleniumDesign.tests.ErrroValidationTest" name="ProductErrorValidation" time="8.888">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at BalajiSoft.SaleniumDesign.tests.ErrroValidationTest.ProductErrorValidation(ErrroValidationTest.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- Errro Validation Test -->
